### ISSUE TITLE
Approve option is not implimented for Outreach Coordinator

### ISSUE THREAD

**Issue by ksripathi** [manjulasoftware/outreach#1]
As per our design when a nodal coordinator uploads the documents in his account outreach coordinator should be able to review it and approve there is no such option is implemented yet.

**Comment by manjulasoftware** [comment]
![screenshot_9](https://cloud.githubusercontent.com/assets/13532745/9466884/876a7d2c-4b55-11e5-9393-1f0f08dfa18f.png)
please check the screenshot for  above  functionality.
