### ISSUE TITLE
Forgot password link not displayed on portal home page though its defined

### ISSUE THREAD

**Issue by anirudhnihalani** [manjulasoftware/outreach#11]
Forgot password anchor tag is defined but it’s not visible on home page.No text is added to anchor tag

**Comment by manjulasoftware** [comment]
forgot password feature is disable now on request  (according to  wireframes there is no feature)

**Comment by ksripathi** [comment]
Hello Manjula,

Close the issues whenever you done with it. Instead you can write a comment about your issue status
