### ISSUE TITLE
Use Mozilla Persona for authentication system

### ISSUE THREAD

**Issue by ksripathi** [manjulasoftware/outreach#7]
Mozilla Persona authentication system is an open source authentication system which will provide us all required api's to verify our user credentials in a secure way using SSL certificates. As our outreach portal is not using any SSL certificates it is advisble to use this or any other such similar services.

**Comment by manjulasoftware** [comment]
As discussed with Geeta, this feature is on hold now, as we have a few doubts regarding this. Once the doubts are clarified we will implement this feature.
